version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=production
      - WATCH_DIR=/wars
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=production

  glassfish:
    image: glassfish
    ports:
      - "8080:8080"
    volumes:
      - ./wars:/opt/glassfish5/glassfish/domains/domain1/autodeploy
